from youtube_transcript_api import YouTubeTranscriptApi
 
# retrieve the available transcripts
transcript_list = YouTubeTranscriptApi.list_transcripts('SW14tOda_kI')
print(transcript_list)
 
# iterate over all available transcripts
for transcript in transcript_list:
 
    # the Transcript object provides metadata
    # properties
    print(
        transcript.video_id,
        transcript.language,
        transcript.language_code,
       
        # whether it has been manually created or
        # generated by YouTube
        transcript.is_generated,
         
        # whether this transcript can be translated 
        # or not
        transcript.is_translatable,
         
        # a list of languages the transcript can be 
        # translated to
        transcript.translation_languages,
    )